### ISSUE TITLE
setting option in .eslintrc

### ISSUE THREAD

**Issue by jamesdixon** [continuationlabs/hapi-scope-start#4]
Apologies in advance for what is most likely a stupid question :)

I'm having trouble finding how to set the `allow-one-liners` option in `.eslintrc`. I tried the following among other things with no luck:

```js
{
    "extends": "hapi",
    "rules": {
        "hapi-scope-start": ["allow-one-liners"]
    }
}
```
Could you point me in the right direct?

Thank you!

**Comment by cjihrig** [comment]
That looks mostly right, but I think you have to say `hapi/hapi-scope-start` in the `rules` section. See [here](https://github.com/continuationlabs/eslint-config-hapi/blob/master/lib/index.js#L31). I'm going to close this, but let me know if that doesn't work.

**Comment by jamesdixon** [comment]
Thanks, @cjihrig - worked like a charm! 

Cheers.
